services:
  app:
    build:
      context: .
      dockerfile: apps/api/Dockerfile
      args:
        - DEV=true
    ports:
      - "8000:8000"
    volumes:
      - ./apps/api:/app
    env_file:
      - ./apps/api/.env
    command: >
      sh -c "uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload"
