"""Initial core tables placeholder.

Revision ID: 0001_init_core_tables
Revises:
Create Date: 2026-04-14 00:00:00
"""

from typing import Sequence

from alembic import op

# revision identifiers, used by Alembic.
# WARNING:
# - This revision has been applied to a persistent Supabase environment.
# - Do not edit this file in place after application.
# - All future schema changes must be introduced as new Alembic revisions.
revision: str = "0001_init_core_tables"
down_revision: str | None = None
branch_labels: Sequence[str] | None = None
depends_on: Sequence[str] | None = None


def upgrade() -> None:
    op.execute("""
        DO $$
        BEGIN
            -- Enum types
            EXECUTE 'DROP TYPE IF EXISTS requested_role_enum CASCADE';
            EXECUTE 'CREATE TYPE requested_role_enum AS ENUM (''DRIVE_TESTER'', ''ADMIN'')';
            EXECUTE 'DROP TYPE IF EXISTS approved_role_enum CASCADE';
            EXECUTE 'CREATE TYPE approved_role_enum AS ENUM (''DRIVE_TESTER'', ''ADMIN'')';
            EXECUTE 'DROP TYPE IF EXISTS account_status_enum CASCADE';
            EXECUTE 'CREATE TYPE account_status_enum AS ENUM (''PENDING_APPROVAL'', ''APPROVED'', ''REJECTED'', ''SUSPENDED'')';
            EXECUTE 'DROP TYPE IF EXISTS zone_enum CASCADE';
            EXECUTE 'CREATE TYPE zone_enum AS ENUM (''NORTHEAST'', ''CENTRAL'', ''SOUTH_FLORIDA'')';
            EXECUTE 'DROP TYPE IF EXISTS shift_enum CASCADE';
            EXECUTE 'CREATE TYPE shift_enum AS ENUM (''AM'', ''PM'')';
            EXECUTE 'DROP TYPE IF EXISTS submission_status_enum CASCADE';
            EXECUTE 'CREATE TYPE submission_status_enum AS ENUM (''ONGOING'', ''COMPLETED'')';
            EXECUTE 'DROP TYPE IF EXISTS approval_requested_role_enum CASCADE';
            EXECUTE 'CREATE TYPE approval_requested_role_enum AS ENUM (''DRIVE_TESTER'', ''ADMIN'')';
            EXECUTE 'DROP TYPE IF EXISTS approval_decision_enum CASCADE';
            EXECUTE 'CREATE TYPE approval_decision_enum AS ENUM (''PENDING'', ''APPROVED'', ''REJECTED'')';
            EXECUTE 'DROP TYPE IF EXISTS audit_action_type_enum CASCADE';
            EXECUTE 'CREATE TYPE audit_action_type_enum AS ENUM (''CREATED'', ''UPDATED'', ''STATUS_CHANGED'', ''COMPLETED'', ''REOPENED'', ''FILE_UPLOADED'', ''FILE_REMOVED'')';
            EXECUTE 'DROP TYPE IF EXISTS audit_source_enum CASCADE';
            EXECUTE 'CREATE TYPE audit_source_enum AS ENUM (''MOBILE'', ''WEB'', ''ADMIN_CONSOLE'', ''SYNC'')';

            -- app_users
            EXECUTE '
                CREATE TABLE IF NOT EXISTS app_users (
                    id UUID PRIMARY KEY,
                    auth_user_id UUID NOT NULL UNIQUE,
                    full_name VARCHAR(255) NOT NULL,
                    email VARCHAR(255) NOT NULL UNIQUE,
                    requested_role requested_role_enum NOT NULL,
                    approved_role approved_role_enum,
                    account_status account_status_enum NOT NULL,
                    approved_at TIMESTAMP WITH TIME ZONE,
                    approved_by_user_id UUID REFERENCES app_users(id),
                    last_login_at TIMESTAMP WITH TIME ZONE,
                    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
                    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()
                )
            ';

            -- submissions
            EXECUTE '
                CREATE TABLE IF NOT EXISTS submissions (
                    id UUID PRIMARY KEY,
                    client_generated_id UUID NOT NULL UNIQUE,
                    owner_user_id UUID NOT NULL REFERENCES app_users(id),
                    submitter_name_snapshot VARCHAR(255) NOT NULL,
                    submitter_email_snapshot VARCHAR(255) NOT NULL,
                    zone zone_enum NOT NULL,
                    work_date DATE NOT NULL,
                    shift shift_enum NOT NULL,
                    team_number VARCHAR(100),
                    ticket_number VARCHAR(100),
                    cluster_name VARCHAR(255) NOT NULL,
                    cluster_name_normalized VARCHAR(255) NOT NULL,
                    number_of_grids INTEGER NOT NULL,
                    skipped_grids INTEGER NOT NULL,
                    force_tested_grids INTEGER NOT NULL,
                    pending_grids INTEGER NOT NULL,
                    completed_grids INTEGER NOT NULL,
                    status submission_status_enum NOT NULL,
                    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
                    created_by_user_id UUID NOT NULL REFERENCES app_users(id),
                    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
                    updated_by_user_id UUID NOT NULL REFERENCES app_users(id),
                    completed_at TIMESTAMP WITH TIME ZONE,
                    completed_by_user_id UUID REFERENCES app_users(id),
                    reopened_at TIMESTAMP WITH TIME ZONE,
                    reopened_by_user_id UUID REFERENCES app_users(id),
                    version_number INTEGER NOT NULL,
                    CONSTRAINT uq_submissions_owner_date_shift_cluster UNIQUE (owner_user_id, work_date, shift, cluster_name_normalized),
                    CONSTRAINT ck_submissions_number_of_grids_non_negative CHECK (number_of_grids >= 0),
                    CONSTRAINT ck_submissions_skipped_grids_non_negative CHECK (skipped_grids >= 0),
                    CONSTRAINT ck_submissions_force_tested_grids_non_negative CHECK (force_tested_grids >= 0),
                    CONSTRAINT ck_submissions_pending_grids_non_negative CHECK (pending_grids >= 0),
                    CONSTRAINT ck_submissions_completed_grids_non_negative CHECK (completed_grids >= 0),
                    CONSTRAINT ck_submissions_grid_math CHECK (completed_grids + pending_grids + skipped_grids = number_of_grids),
                    CONSTRAINT ck_submissions_skipped_lte_total CHECK (skipped_grids <= number_of_grids),
                    CONSTRAINT ck_submissions_pending_lte_total CHECK (pending_grids <= number_of_grids),
                    CONSTRAINT ck_submissions_completed_lte_total CHECK (completed_grids <= number_of_grids)
                )
            ';

            -- submission_attachments
            EXECUTE '
                CREATE TABLE IF NOT EXISTS submission_attachments (
                    id UUID PRIMARY KEY,
                    submission_id UUID NOT NULL REFERENCES submissions(id),
                    file_name VARCHAR(255) NOT NULL,
                    bucket_name VARCHAR(255) NOT NULL,
                    object_path VARCHAR(500) NOT NULL,
                    mime_type VARCHAR(100) NOT NULL,
                    file_extension VARCHAR(20) NOT NULL,
                    file_size_bytes BIGINT NOT NULL,
                    uploaded_by_user_id UUID NOT NULL REFERENCES app_users(id),
                    uploaded_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
                    is_active BOOLEAN NOT NULL
                )
            ';

            -- submission_audit_logs
            EXECUTE '
                CREATE TABLE IF NOT EXISTS submission_audit_logs (
                    id UUID PRIMARY KEY,
                    submission_id UUID NOT NULL REFERENCES submissions(id),
                    action_type audit_action_type_enum NOT NULL,
                    actor_user_id UUID NOT NULL REFERENCES app_users(id),
                    actor_role VARCHAR(50) NOT NULL,
                    source audit_source_enum NOT NULL,
                    changed_fields_json JSONB,
                    before_snapshot_json JSONB,
                    after_snapshot_json JSONB,
                    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()
                )
            ';

            -- user_approval_audit
            EXECUTE '
                CREATE TABLE IF NOT EXISTS user_approval_audit (
                    id UUID PRIMARY KEY,
                    user_id UUID NOT NULL REFERENCES app_users(id),
                    requested_role approval_requested_role_enum NOT NULL,
                    decision approval_decision_enum NOT NULL,
                    reviewed_by_user_id UUID REFERENCES app_users(id),
                    reviewed_at TIMESTAMP WITH TIME ZONE,
                    review_notes TEXT,
                    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()
                )
            ';
        END;
        $$
    """)


def downgrade() -> None:
    op.execute("""
        DO $$
        BEGIN
            EXECUTE 'DROP TABLE IF EXISTS user_approval_audit';
            EXECUTE 'DROP TABLE IF EXISTS submission_audit_logs';
            EXECUTE 'DROP TABLE IF EXISTS submission_attachments';
            EXECUTE 'DROP TABLE IF EXISTS submissions';
            EXECUTE 'DROP TABLE IF EXISTS app_users';
            EXECUTE 'DROP TYPE IF EXISTS audit_source_enum';
            EXECUTE 'DROP TYPE IF EXISTS audit_action_type_enum';
            EXECUTE 'DROP TYPE IF EXISTS approval_decision_enum';
            EXECUTE 'DROP TYPE IF EXISTS approval_requested_role_enum';
            EXECUTE 'DROP TYPE IF EXISTS submission_status_enum';
            EXECUTE 'DROP TYPE IF EXISTS shift_enum';
            EXECUTE 'DROP TYPE IF EXISTS zone_enum';
            EXECUTE 'DROP TYPE IF EXISTS account_status_enum';
            EXECUTE 'DROP TYPE IF EXISTS approved_role_enum';
            EXECUTE 'DROP TYPE IF EXISTS requested_role_enum';
        END;
        $$
    """)
